Here is the RegmuNet tool.
Author: Nhan Nguyen, see [GitHub](https://github.com/NhanNguyen000/RegmuNet).
Date: `r format(Sys.time(), '%d %B, %Y')`

## How to use the tools
This webpage tool is suitable for small data (less then 5MB, based on Rshiny server retriction) and do not require coding skill. For bigger dataset, it is better to use the code in [GitHub](https://github.com/NhanNguyen000/RegmuNet) and run in a local computer.

You could upload the sample and your reference database, then click on the [Main Page] and wait (2-3 minutes) to see the result.
Other suggestions/selection options?


## Regulatory database
The defaut regulatory reference based on [the database of human transcription factor targets](http://bioinfo.life.hust.edu.cn/hTFtarget#!/), Zhang,Q. et al. (2020) "hTFtarget: a comprehensive database for regulations of human transcription factors and their targets". Genomics, Proteomics & Bioinformatics, [doi:10.1016/j.gpb.2019.09.006](https://doi.org/10.1016/j.gpb.2019.09.006).
